import type { LifecycleUnit, QuizQuestion } from "./types";

// The seven lifecycle slices of the pie, in the order a deal is actually run.
// hue drives each slice's color on the wheel.
export const UNITS: LifecycleUnit[] = [
	{
		"id": "find",
		"label": "Find",
		"title": "Find the Opportunity",
		"blurb": "Spot the right notices and read the set-aside before anyone else.",
		"hue": 210
	},
	{
		"id": "shape",
		"label": "Shape",
		"title": "Shape the Requirement",
		"blurb": "Influence the acquisition early — without tripping an OCI.",
		"hue": 265
	},
	{
		"id": "bid-no-bid",
		"label": "Bid?",
		"title": "Bid / No-Bid",
		"blurb": "Decide where you can actually win before you spend B&P.",
		"hue": 22
	},
	{
		"id": "vehicle",
		"label": "Vehicle",
		"title": "Pick the Vehicle",
		"blurb": "Schedule, IDIQ, GWAC, BPA, or open market — pick the lane.",
		"hue": 158
	},
	{
		"id": "team",
		"label": "Team",
		"title": "Team & Subcontract",
		"blurb": "CTAs, JVs, and the 50% rule — build a compliant winning team.",
		"hue": 330
	},
	{
		"id": "propose",
		"label": "Propose",
		"title": "Write the Proposal",
		"blurb": "Answer Section L, win on Section M, stay responsive.",
		"hue": 44
	},
	{
		"id": "win-protest",
		"label": "Win",
		"title": "Win & Protest",
		"blurb": "Debriefings, protests, and the CICA stay clock.",
		"hue": 4
	}
];

// Authored + adversarially fact-checked against the FAR by a subagent fleet,
// then difficulty-tagged (recall = fundamentals; scenarios = core/advanced).
// Regenerated by scripts — edit the source workflow, not this array, to change.
export const QUESTIONS: QuizQuestion[] = [
	{
		"id": "find-sam-registration-timing",
		"unitId": "find",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "Under FAR 52.204-7 (System for Award Management), when must an offeror be registered in SAM?",
		"options": [
			{
				"id": "a",
				"text": "When submitting the offer, and continuously through award, performance, and final payment.",
				"correct": true
			},
			{
				"id": "b",
				"text": "Only after being selected as the apparent awardee, before the contract is signed.",
				"correct": false
			},
			{
				"id": "c",
				"text": "Within 30 days after contract award.",
				"correct": false
			},
			{
				"id": "d",
				"text": "Only for awards above the simplified acquisition threshold of $250,000.",
				"correct": false
			}
		],
		"explanation": "FAR 52.204-7(b) requires the offeror to be registered in SAM at the time it submits its offer and to remain registered through award, performance, and final payment. It is not deferred until after selection and is not tied to the SAT.",
		"citation": "FAR 52.204-7",
		"sourceUrl": "https://www.acquisition.gov/far/52.204-7",
		"tags": [
			"sam-registration",
			"52.204-7",
			"eligibility"
		]
	},
	{
		"id": "find-sources-sought-capture",
		"unitId": "find",
		"format": "scenario",
		"difficulty": "core",
		"scoring": "tiered",
		"situation": "A sources sought notice posts on SAM.gov for work your firm can perform. The requirement is currently unrestricted (no set-aside), and your company is a large business.",
		"prompt": "What is the strongest capture move?",
		"options": [
			{
				"id": "a",
				"text": "Respond with a tailored capability statement showing you are an interested, capable source, and use it to shape scope with the contracting shop.",
				"tier": "best"
			},
			{
				"id": "b",
				"text": "Do nothing and wait for the formal RFP to drop.",
				"tier": "costly"
			},
			{
				"id": "c",
				"text": "Submit a full priced technical proposal in response to the notice.",
				"tier": "disqualifying"
			},
			{
				"id": "d",
				"text": "File a bid protest arguing the notice is defective.",
				"tier": "disqualifying"
			}
		],
		"explanation": "A sources sought is market research under FAR Part 10 — no award results from it. Responding with a capability statement puts a capable large business on record (informing the CO's set-aside decision) and opens the door to shape requirements. It is not a solicitation, so there is nothing to price and nothing to protest.",
		"citation": "FAR 10.002",
		"sourceUrl": "https://www.acquisition.gov/far/10.002",
		"tags": [
			"sources-sought",
			"market-research",
			"part-10"
		]
	},
	{
		"id": "find-large-biz-sb-setaside",
		"unitId": "find",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "reveal-tradeoff",
		"situation": "You review a notice on SAM.gov that is a total small business set-aside under a NAICS code whose size standard your firm clearly exceeds. Proposals are due in three weeks.",
		"prompt": "How should you pursue this opportunity?",
		"options": [
			{
				"id": "a",
				"text": "Submit as prime anyway and argue your qualifications on the merits.",
				"tier": "disqualifying",
				"consequence": "Rejected as ineligible — only small businesses may compete on a total SB set-aside (FAR 19.502-2). Wasted B&D and a size protest waiting to happen."
			},
			{
				"id": "b",
				"text": "Team as a subcontractor to a qualified small business prime.",
				"tier": "best",
				"consequence": "You capture scope on the work, but the small prime must meet the limitations on subcontracting (self-perform the required share), capping how much you can take."
			},
			{
				"id": "c",
				"text": "Stand up an SBA mentor-protege joint venture with a small business and bid as the JV.",
				"tier": "costly",
				"consequence": "Legitimate path — an approved MPP JV can bid as small — but SBA approval takes months, so you almost certainly cannot get it in place before proposals are due."
			},
			{
				"id": "d",
				"text": "No-bid this one and position now for the next unrestricted follow-on.",
				"tier": "defensible",
				"consequence": "You concede this award but preserve B&D dollars and relationships for a competition you can actually win as prime."
			}
		],
		"explanation": "A total small business set-aside restricts prime eligibility to small businesses (FAR 19.502-2), and size is measured against the NAICS code assigned to the solicitation. A large firm's realistic near-term play is to subcontract to a small prime; an MPP joint venture is valid but too slow for a three-week deadline.",
		"citation": "FAR 19.502-2",
		"sourceUrl": "https://www.acquisition.gov/far/19.502-2",
		"tags": [
			"set-aside",
			"small-business",
			"naics",
			"teaming"
		]
	},
	{
		"id": "find-hubzone-identify",
		"unitId": "find",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "confidence-bet",
		"situation": "You are triaging set-aside notices. One restricts competition to firms whose principal office is located in a designated area and that have at least 35% of their employees residing in such an area.",
		"prompt": "Which set-aside program is this?",
		"options": [
			{
				"id": "a",
				"text": "HUBZone",
				"correct": true
			},
			{
				"id": "b",
				"text": "SDVOSB (Service-Disabled Veteran-Owned Small Business)",
				"correct": false
			},
			{
				"id": "c",
				"text": "8(a) Business Development",
				"correct": false
			},
			{
				"id": "d",
				"text": "WOSB (Women-Owned Small Business)",
				"correct": false
			}
		],
		"explanation": "The principal-office-in-a-HUBZone plus 35%-of-employees-residing-in-a-HUBZone test is unique to the HUBZone program (FAR 19.1303). SDVOSB keys on service-disabled veteran ownership and control, 8(a) on disadvantaged ownership plus SBA program admission, and WOSB on women ownership and control.",
		"citation": "FAR 19.1303",
		"sourceUrl": "https://www.acquisition.gov/far/19.1303",
		"tags": [
			"set-aside",
			"hubzone",
			"socioeconomic-programs"
		]
	},
	{
		"id": "shape-rfi-nonbinding",
		"unitId": "shape",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "Under FAR 15.201, what is the legal status of your company's response to a Request for Information (RFI)?",
		"options": [
			{
				"id": "a",
				"text": "It is not an offer and cannot be accepted by the Government to form a binding contract",
				"correct": true
			},
			{
				"id": "b",
				"text": "It is a binding offer the Government may accept at any time within 30 days",
				"correct": false
			},
			{
				"id": "c",
				"text": "It obligates the Government to include your firm on the resulting solicitation's bidders list",
				"correct": false
			},
			{
				"id": "d",
				"text": "It is a formal proposal that will be evaluated and scored for award",
				"correct": false
			}
		],
		"explanation": "FAR 15.201(e) states RFIs are used when the Government does not presently intend to award a contract but wants planning/market information; responses are not offers and cannot be accepted to form a binding contract. An RFI is market research, not a solicitation.",
		"citation": "FAR 15.201(e)",
		"sourceUrl": "https://www.acquisition.gov/far/15.201",
		"tags": [
			"rfi",
			"market-research",
			"far-15.201",
			"non-binding"
		]
	},
	{
		"id": "shape-rule-of-two-threshold",
		"unitId": "shape",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "Under the 'rule of two' (FAR 19.502-2(b)), when must the contracting officer set aside an acquisition exceeding the simplified acquisition threshold for small business?",
		"options": [
			{
				"id": "a",
				"text": "When there is a reasonable expectation of offers from at least two responsible small businesses and award will be at fair market price",
				"correct": true
			},
			{
				"id": "b",
				"text": "Whenever at least two large businesses have expressed interest in the requirement",
				"correct": false
			},
			{
				"id": "c",
				"text": "Only when the acquisition is below the $10,000 micro-purchase threshold",
				"correct": false
			},
			{
				"id": "d",
				"text": "When at least three small businesses submit capability statements, regardless of price",
				"correct": false
			}
		],
		"explanation": "FAR 19.502-2(b) requires set-aside of acquisitions over the simplified acquisition threshold ($250,000) when the CO reasonably expects offers from at least two responsible small business concerns and award at fair market price. This 'two + fair price' test is the leverage point a small prime targets with its sources-sought response.",
		"citation": "FAR 19.502-2(b)",
		"sourceUrl": "https://www.acquisition.gov/far/19.502-2",
		"tags": [
			"rule-of-two",
			"set-aside",
			"far-19.502-2",
			"small-business"
		]
	},
	{
		"id": "shape-unequal-access-oci",
		"unitId": "shape",
		"format": "scenario",
		"difficulty": "core",
		"scoring": "tiered",
		"situation": "Your firm holds an advisory support contract that gives your staff access to other offerors' proprietary data and nonpublic Government procurement-sensitive information. A related competitive requirement is coming that you want to bid on.",
		"prompt": "What's the right move to preserve your eligibility?",
		"options": [
			{
				"id": "a",
				"text": "Proactively propose a firewall / nondisclosure mitigation plan and get the contracting officer's agreement before pursuing the new opportunity",
				"tier": "best"
			},
			{
				"id": "b",
				"text": "Voluntarily wall off and recuse the exposed staff, forgoing any use of that team on the bid",
				"tier": "defensible"
			},
			{
				"id": "c",
				"text": "Bid and quietly use the nonpublic information to sharpen your proposal",
				"tier": "disqualifying"
			},
			{
				"id": "d",
				"text": "Assume there's no conflict because access to information is only an OCI if you wrote the specification",
				"tier": "disqualifying"
			}
		],
		"explanation": "FAR 9.505-4 (unequal access to information) triggers when a firm gains access to nonpublic information that would give it a competitive advantage. Unlike biased ground rules, this type CAN be mitigated — an approved firewall/NDA plan agreed with the CO is the standard cure; misusing the info or ignoring the conflict is disqualifying.",
		"citation": "FAR 9.505-4",
		"sourceUrl": "https://www.acquisition.gov/far/9.505-4",
		"tags": [
			"oci",
			"unequal-access",
			"far-9.505-4",
			"mitigation"
		]
	},
	{
		"id": "shape-naics-steering",
		"unitId": "shape",
		"format": "scenario",
		"difficulty": "core",
		"scoring": "single-best",
		"situation": "The NAICS code the agency plans to assign carries a size standard under which your firm would be 'other than small.' A different, defensible NAICS code for the same work carries a higher size standard that would keep you small.",
		"prompt": "What is the best way to pursue the more favorable NAICS designation?",
		"options": [
			{
				"id": "a",
				"text": "Advocate the appropriate NAICS during market research/RFI exchanges, and if the CO still designates an incorrect one, file a NAICS appeal with SBA OHA within 10 days of the solicitation",
				"correct": true
			},
			{
				"id": "b",
				"text": "You cannot influence the NAICS code; it is fixed by the product/service and never reviewable",
				"correct": false
			},
			{
				"id": "c",
				"text": "File a NAICS appeal with GAO within 10 days of award",
				"correct": false
			},
			{
				"id": "d",
				"text": "Simply self-certify under whichever NAICS keeps you small when you submit your proposal",
				"correct": false
			}
		],
		"explanation": "The CO designates the NAICS code (FAR 19.303), which sets the size standard. You influence it early through market-research input; a formal challenge is a NAICS appeal to the SBA Office of Hearings and Appeals (OHA), filed within 10 calendar days after the solicitation is issued — not GAO, and not by unilateral self-certification.",
		"citation": "FAR 19.303(c)",
		"sourceUrl": "https://www.acquisition.gov/far/19.303",
		"tags": [
			"naics",
			"size-standard",
			"far-19.303",
			"sba-oha"
		]
	},
	{
		"id": "shape-biased-ground-rules-oci",
		"unitId": "shape",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "reveal-tradeoff",
		"situation": "An agency program office you've been courting asks your firm to draft the full Statement of Work and specifications for an upcoming competitive RFP 'as a trusted advisor,' free of charge. You fully intend to bid on that RFP once it's released.",
		"prompt": "How do you respond?",
		"options": [
			{
				"id": "a",
				"text": "Decline to author the SOW, but submit a capability statement and an unsolicited white paper recommending requirements and outcomes",
				"tier": "best",
				"consequence": "Shapes the requirement toward your strengths while keeping you eligible to compete — the intended play."
			},
			{
				"id": "b",
				"text": "Draft the complete SOW and specifications exactly as requested to build goodwill",
				"tier": "disqualifying",
				"consequence": "Creates a 'biased ground rules' OCI under FAR 9.505-2; you'd be excluded from competing on the resulting RFP."
			},
			{
				"id": "c",
				"text": "Have a separate corporate subsidiary write the SOW so your bidding entity stays clean",
				"tier": "costly",
				"consequence": "OCI is generally imputed across the corporate family; a firewall rarely cures biased ground rules, so you likely still get excluded."
			},
			{
				"id": "d",
				"text": "Write the SOW and simply disclose it in your proposal, assuming disclosure cures the conflict",
				"tier": "disqualifying",
				"consequence": "Disclosure doesn't cure biased ground rules — the standard remedy is avoidance/exclusion, so you're out."
			}
		],
		"explanation": "FAR 9.505-2 (biased ground rules) generally bars a firm that prepared the specs/SOW from competing, because it could skew the requirement to itself. This OCI type is avoided, not mitigated; disclosure or a firewall won't save the bid. Shape through RFI/white-paper input instead of authoring the actual solicitation.",
		"citation": "FAR 9.505-2",
		"sourceUrl": "https://www.acquisition.gov/far/9.505-2",
		"tags": [
			"oci",
			"biased-ground-rules",
			"far-9.505-2",
			"shaping"
		]
	},
	{
		"id": "shape-sources-sought-set-aside",
		"unitId": "shape",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "confidence-bet",
		"situation": "You're a small business. The agency posts a sources-sought notice for a $1.2M requirement and internal signals suggest it's leaning toward a full-and-open competition. You'd rather see it set aside for small business.",
		"prompt": "What is the single most effective action to steer the acquisition toward a small-business set-aside?",
		"options": [
			{
				"id": "a",
				"text": "Submit a sources-sought response documenting your firm's capability and relevant past performance so the CO can find a reasonable expectation of two-plus capable small businesses",
				"correct": true
			},
			{
				"id": "b",
				"text": "File a size-standard protest with the SBA before any solicitation exists",
				"correct": false
			},
			{
				"id": "c",
				"text": "Submit a binding priced offer in response to the sources-sought notice",
				"correct": false
			},
			{
				"id": "d",
				"text": "Wait for the RFP and then protest the lack of a set-aside to GAO",
				"correct": false
			}
		],
		"explanation": "The rule of two (FAR 19.502-2(b)) turns on the CO's market-research finding that two-plus responsible small businesses will offer at a fair price. A strong, capability-rich sources-sought response is exactly the evidence that supports that finding — the pre-solicitation window is where a set-aside is won. A sources-sought response is not an offer, and protests come far too late (and cost less leverage) than shaping the market research.",
		"citation": "FAR 19.502-2(b)",
		"sourceUrl": "https://www.acquisition.gov/far/19.502-2",
		"tags": [
			"sources-sought",
			"set-aside",
			"rule-of-two",
			"far-19.502-2"
		]
	},
	{
		"id": "shape-draft-rfp-industry-day",
		"unitId": "shape",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "reveal-tradeoff",
		"situation": "The agency releases a Draft RFP and schedules an industry day. You want the final RFP's evaluation factors and SOW to reward your firm's genuine discriminators.",
		"prompt": "What's your play?",
		"options": [
			{
				"id": "a",
				"text": "Submit written comments on the Draft RFP recommending evaluation factors and outcomes that map to your real strengths",
				"tier": "best",
				"consequence": "Legitimately shapes the RFP; the final terms are visible to all offerors, so no OCI — and your P-win improves."
			},
			{
				"id": "b",
				"text": "Offer privately to rewrite sections of the SOW for the CO after industry day",
				"tier": "disqualifying",
				"consequence": "Authoring the SOW is a biased-ground-rules OCI (FAR 9.505-2); you're excluded from the competition."
			},
			{
				"id": "c",
				"text": "Ask the CO one-on-one for the incumbent's nonpublic contract terms and pricing",
				"tier": "disqualifying",
				"consequence": "Seeking procurement-sensitive/proprietary data creates an unequal-access OCI and integrity concerns — poisons your bid."
			},
			{
				"id": "d",
				"text": "Stay silent to avoid any OCI risk and just respond to the final RFP",
				"tier": "costly",
				"consequence": "Safe, but forfeits the cheapest window to shape terms; competitors who commented set the ground rules against you."
			}
		],
		"explanation": "FAR 15.201 encourages pre-solicitation exchanges precisely so industry can improve the requirement; commenting on a Draft RFP or at industry day is the sanctioned, OCI-free way to shape terms because the resulting solicitation is public to all. Authoring the SOW or extracting nonpublic data crosses into FAR 9.5 OCI territory.",
		"citation": "FAR 15.201",
		"sourceUrl": "https://www.acquisition.gov/far/15.201",
		"tags": [
			"draft-rfp",
			"industry-day",
			"far-15.201",
			"oci",
			"shaping"
		]
	},
	{
		"id": "bid-no-bid-rule-of-two-trigger",
		"unitId": "bid-no-bid",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "Under the \"rule of two\" (FAR 19.502-2), when must a contracting officer set aside an acquisition above the simplified acquisition threshold for small business?",
		"options": [
			{
				"id": "a",
				"text": "When there is a reasonable expectation of offers from at least two responsible small business concerns and award will be made at fair market prices",
				"correct": true
			},
			{
				"id": "b",
				"text": "When at least two 8(a)-certified firms have expressed interest through a sources-sought notice",
				"correct": false
			},
			{
				"id": "c",
				"text": "When any two firms of any size are expected to submit compliant proposals",
				"correct": false
			},
			{
				"id": "d",
				"text": "When two or more small businesses are already on the incumbent contract's team",
				"correct": false
			}
		],
		"explanation": "FAR 19.502-2(b) requires a set-aside when the CO reasonably expects offers from at least two responsible small businesses AND award at fair market prices. Both prongs must hold; the rule is not limited to 8(a) firms and 'any size' or incumbency does not trigger it.",
		"citation": "FAR 19.502-2",
		"sourceUrl": "https://www.acquisition.gov/far/19.502-2",
		"tags": [
			"rule-of-two",
			"set-aside",
			"small-business",
			"eligibility"
		]
	},
	{
		"id": "bid-no-bid-sam-responsibility-gate",
		"unitId": "bid-no-bid",
		"format": "scenario",
		"difficulty": "core",
		"scoring": "tiered",
		"situation": "Proposals are due in eight days on a competitive RFP you want to win. During your bid-readiness check you discover your SAM.gov registration lapsed last month and has not been renewed.",
		"prompt": "What is the right move to protect the bid?",
		"options": [
			{
				"id": "a",
				"text": "Renew and fully activate the SAM registration now so it is active at time of offer, then submit",
				"tier": "best"
			},
			{
				"id": "b",
				"text": "Submit the proposal on time and complete the SAM renewal before award is announced",
				"tier": "disqualifying"
			},
			{
				"id": "c",
				"text": "No-bid this one and prioritize keeping SAM current for the next opportunity",
				"tier": "defensible"
			},
			{
				"id": "d",
				"text": "Ask the contracting officer for a blanket waiver of the SAM requirement given your long track record",
				"tier": "costly"
			}
		],
		"explanation": "FAR 52.204-7 requires an offeror to be registered in SAM at the time it submits its offer and continuously through award; it is a gating matter, not a curable post-submission item. Renewing before offer preserves the bid; submitting unregistered risks elimination, and COs cannot simply waive the requirement.",
		"citation": "FAR 52.204-7",
		"sourceUrl": "https://www.acquisition.gov/far/52.204-7",
		"tags": [
			"sam-registration",
			"responsibility",
			"gate",
			"bid-readiness"
		]
	},
	{
		"id": "bid-no-bid-large-prime-on-setaside",
		"unitId": "bid-no-bid",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "reveal-tradeoff",
		"situation": "You run capture at a large prime. The sources-sought responses show at least three capable small businesses that do this exact work, and the draft RFP signals a total small-business set-aside under the rule of two. The requirement is squarely in your wheelhouse and you want in.",
		"prompt": "How do you position the company to capture work on this set-aside?",
		"options": [
			{
				"id": "a",
				"text": "Submit as prime and argue your past performance justifies an exception to the set-aside",
				"tier": "disqualifying",
				"consequence": "Proposal is found ineligible as an other-than-small concern on a total set-aside; B&P is wasted and you signal to the customer you don't understand the acquisition."
			},
			{
				"id": "b",
				"text": "Team as a subcontractor under a capable small-business prime",
				"tier": "best",
				"consequence": "You are eligible for the work, but the small prime must meet the limitations on subcontracting (perform at least 50% of the cost of services itself), capping your share."
			},
			{
				"id": "c",
				"text": "Stand up an SBA mentor-protege joint venture so the JV can compete as small",
				"tier": "defensible",
				"consequence": "Viable and lets you share prime-level scope, but only if an SBA-approved mentor-protege agreement and JV are in place before offer — usually too little lead time on an imminent RFP."
			},
			{
				"id": "d",
				"text": "File an agency-level protest challenging the set-aside decision to force full-and-open",
				"tier": "costly",
				"consequence": "Rarely succeeds once the rule of two is met on the record, delays the deal, and burns the customer relationship you need for the next opportunity."
			}
		],
		"explanation": "On a total small-business set-aside a large business cannot prime; the reliable eligible path is subcontracting under a small prime (subject to FAR 52.219-14 limitations on subcontracting). A mentor-protege JV works only if approved and structured in advance; protesting a valid rule-of-two set-aside is a low-odds, relationship-damaging move.",
		"citation": "FAR 19.502-2",
		"sourceUrl": "https://www.acquisition.gov/far/19.502-2",
		"tags": [
			"set-aside",
			"teaming",
			"subcontracting",
			"mentor-protege",
			"large-prime"
		]
	},
	{
		"id": "bid-no-bid-incumbent-recompete-pwin",
		"unitId": "bid-no-bid",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "confidence-bet",
		"situation": "You are the challenger on an incumbent recompete. Section M is a best-value tradeoff where past performance on this specific scope is the highest-weighted factor, the incumbent is well-regarded by the customer, and the requirements read as tightly aligned to how the incumbent already operates. Your relevant past performance is thin and you have no clear technical or price discriminator.",
		"prompt": "What is the strongest single reason to no-bid this pursuit?",
		"options": [
			{
				"id": "a",
				"text": "Section M weights same-scope past performance highest, the incumbent holds that advantage, and you have no discriminator — probability of win is too low to justify the B&P investment",
				"correct": true
			},
			{
				"id": "b",
				"text": "You can technically meet every minimum requirement listed in Section L",
				"correct": false
			},
			{
				"id": "c",
				"text": "You could bid the lowest price and win on cost",
				"correct": false
			},
			{
				"id": "d",
				"text": "Incumbents statistically almost always lose on recompete, so the odds favor you",
				"correct": false
			}
		],
		"explanation": "In a tradeoff source selection (FAR 15.101-1), low Pwin driven by the most-weighted factor plus no discriminator is the classic no-bid signal. Meeting Section L minimums is table stakes, price is not the deciding lever in a best-value tradeoff, and 'incumbents always lose' is a false generalization.",
		"citation": "FAR 15.101-1",
		"sourceUrl": "https://www.acquisition.gov/far/15.101-1",
		"tags": [
			"incumbent",
			"pwin",
			"section-m",
			"tradeoff",
			"no-bid"
		]
	},
	{
		"id": "vehicle-thresholds-recall",
		"unitId": "vehicle",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "In federal contracting, the micro-purchase threshold and the simplified acquisition threshold (SAT) are, respectively:",
		"options": [
			{
				"id": "a",
				"text": "$10,000 and $250,000",
				"correct": true
			},
			{
				"id": "b",
				"text": "$3,500 and $150,000",
				"correct": false
			},
			{
				"id": "c",
				"text": "$10,000 and $150,000",
				"correct": false
			},
			{
				"id": "d",
				"text": "$25,000 and $250,000",
				"correct": false
			}
		],
		"explanation": "FAR 2.101 sets the micro-purchase threshold at $10,000 and the simplified acquisition threshold at $250,000. The $3,500/$150,000 pair is the pre-2018 values; knowing the current numbers tells you which streamlined buying path a requirement can ride.",
		"citation": "FAR 2.101",
		"sourceUrl": "https://www.acquisition.gov/far/2.101",
		"tags": [
			"thresholds",
			"micro-purchase",
			"SAT",
			"FAR-2.101"
		]
	},
	{
		"id": "vehicle-gwac-definition",
		"unitId": "vehicle",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "Which best describes a Governmentwide Acquisition Contract (GWAC), such as Alliant 2, 8(a) STARS III, or VETS 2?",
		"options": [
			{
				"id": "a",
				"text": "A pre-established, multiple-award IDIQ contract for IT solutions that any federal agency can place task orders against",
				"correct": true
			},
			{
				"id": "b",
				"text": "A GSA Multiple Award Schedule (MAS) contract offering commercial products and services at negotiated ceiling prices",
				"correct": false
			},
			{
				"id": "c",
				"text": "A single-agency IDIQ contract available only to the agency that awarded it",
				"correct": false
			},
			{
				"id": "d",
				"text": "A Blanket Purchase Agreement established against a schedule to fill recurring needs",
				"correct": false
			}
		],
		"explanation": "FAR 2.101 defines a GWAC as a task-order or delivery-order contract for information technology, established by one agency for governmentwide use. It is an IDIQ vehicle any agency can order from, which is what distinguishes it from an agency-specific IDIQ, a Schedule (MAS), or a BPA.",
		"citation": "FAR 2.101",
		"sourceUrl": "https://www.acquisition.gov/far/2.101",
		"tags": [
			"GWAC",
			"IDIQ",
			"IT",
			"FAR-2.101"
		]
	},
	{
		"id": "vehicle-idiq-fair-opportunity",
		"unitId": "vehicle",
		"format": "scenario",
		"difficulty": "core",
		"scoring": "single-best",
		"situation": "Your firm is one of five awardees on a multiple-award IDIQ contract. A new $2M requirement arises that falls squarely within the IDIQ's scope. Your capture lead asks how the agency will decide who gets the work.",
		"prompt": "How is a task order of this size awarded under a multiple-award IDIQ?",
		"options": [
			{
				"id": "a",
				"text": "The agency must give each awardee a fair opportunity to be considered, typically through a task-order competition among the IDIQ holders",
				"correct": true
			},
			{
				"id": "b",
				"text": "The agency may sole-source it to any one awardee, since all holders already won the base IDIQ",
				"correct": false
			},
			{
				"id": "c",
				"text": "It must be re-competed on the open market under FAR Part 15 full-and-open competition",
				"correct": false
			},
			{
				"id": "d",
				"text": "It is awarded automatically to whichever awardee holds the lowest base IDIQ pricing",
				"correct": false
			}
		],
		"explanation": "FAR 16.505 requires that each awardee on a multiple-award IDIQ be given a fair opportunity to be considered for orders above the micro-purchase threshold, absent a documented exception. For a $2M order that means a task-order competition among the holders, not a sole source or a fresh open-market buy.",
		"citation": "FAR 16.505",
		"sourceUrl": "https://www.acquisition.gov/far/16.505",
		"tags": [
			"IDIQ",
			"task-order",
			"fair-opportunity",
			"FAR-16.505"
		]
	},
	{
		"id": "vehicle-cta-vs-subcontract",
		"unitId": "vehicle",
		"format": "scenario",
		"difficulty": "core",
		"scoring": "tiered",
		"situation": "A GSA Schedule task order needs both cybersecurity engineering and cloud migration labor. Your firm holds a MAS contract covering the cyber work but not the cloud labor categories. A partner firm holds its own MAS contract that does cover the cloud categories. Neither the underlying requirement nor the order is set aside for any socioeconomic program.",
		"prompt": "What is the strongest way to team so both companies contribute and get paid under the Schedule order?",
		"options": [
			{
				"id": "a",
				"text": "Form a Schedules Contractor Team Arrangement (CTA) where each member holds a MAS contract and contributes its own SINs and pricing to the order",
				"tier": "best"
			},
			{
				"id": "b",
				"text": "Bring the partner in as a subcontractor under your prime Schedule order",
				"tier": "defensible"
			},
			{
				"id": "c",
				"text": "Stand up an 8(a) joint venture to pursue the order together",
				"tier": "costly"
			},
			{
				"id": "d",
				"text": "Add the partner's cloud labor to your order as open-market items",
				"tier": "disqualifying"
			}
		],
		"explanation": "A Schedules CTA lets each teammate contribute the labor categories from its own MAS contract, so the customer buys everything at negotiated Schedule pricing and both firms have privity for their portion (FAR 9.601 contractor team arrangement). A subcontract works but buries the partner's Schedule pricing under yours; an 8(a) JV is a set-aside socioeconomic construct irrelevant to an unrestricted order; adding the partner's labor as open-market defeats the point of using the Schedule and misrepresents it.",
		"citation": "FAR 9.601",
		"sourceUrl": "https://www.acquisition.gov/far/9.601",
		"tags": [
			"CTA",
			"teaming",
			"GSA-Schedule",
			"subcontract",
			"FAR-9.601"
		]
	},
	{
		"id": "vehicle-open-market-on-schedule",
		"unitId": "vehicle",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "reveal-tradeoff",
		"situation": "You hold a GSA MAS (Schedule) contract. A customer wants to place a single order: most of the items map to your Schedule SINs, but two line items are products you do not carry on your Schedule (open-market items). The customer wants it all on one order to save time.",
		"prompt": "How do you steer the deal?",
		"options": [
			{
				"id": "a",
				"text": "Identify the two non-Schedule line items as open-market on the order and make sure the CO establishes their price reasonableness and follows simplified acquisition procedures for them",
				"tier": "best",
				"consequence": "Clean order: the Schedule items ride your MAS terms and the open-market items are documented separately per FAR 8.402(f). You keep the full sale and no compliance flag."
			},
			{
				"id": "b",
				"text": "Roll the two open-market items onto the order as if they were Schedule items to keep it a single, simple Schedule buy",
				"tier": "disqualifying",
				"consequence": "Selling open-market goods at Schedule terms misrepresents your contract; the order can be cancelled and your MAS contract flagged in a GSA audit."
			},
			{
				"id": "c",
				"text": "Tell the customer to issue a separate open-market purchase elsewhere for the two items",
				"tier": "defensible",
				"consequence": "Compliant, but you hand that revenue to a competitor and add procurement lead time the customer wanted to avoid."
			},
			{
				"id": "d",
				"text": "Decline the whole order because a Schedule order cannot include non-Schedule items",
				"tier": "costly",
				"consequence": "You walk away from revenue you could have kept: FAR expressly permits open-market items on a Schedule order when they are identified and handled under Part 13."
			}
		],
		"explanation": "FAR 8.402(f) allows a CO to add open-market (non-Schedule) items to a Schedule order only when they are clearly labeled as open-market and the applicable acquisition rules (competition, price reasonableness) are followed for those items. Mixing them silently into Schedule pricing is a misrepresentation.",
		"citation": "FAR 8.402(f)",
		"sourceUrl": "https://www.acquisition.gov/far/8.402",
		"tags": [
			"GSA-Schedule",
			"MAS",
			"open-market",
			"FAR-8.402"
		]
	},
	{
		"id": "team-gsa-cta-vs-prime-sub-privity",
		"unitId": "team",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "In a GSA Schedules Contractor Team Arrangement (CTA), how does each team member's relationship to the Government differ from a FAR 9.6 prime/subcontractor team?",
		"options": [
			{
				"id": "a",
				"text": "Each CTA member holds its own GSA Schedule contract and is in privity with the Government for the portion it performs; there is no prime/subcontractor hierarchy.",
				"correct": true
			},
			{
				"id": "b",
				"text": "One member is designated team lead, holds the order, and the others perform as its subcontractors with no privity to the Government.",
				"correct": false
			},
			{
				"id": "c",
				"text": "One member is the managing venturer of a joint venture that alone holds the order and signs on the team's behalf.",
				"correct": false
			},
			{
				"id": "d",
				"text": "SBA must approve the CTA and certify the combined team as a single small business before award.",
				"correct": false
			}
		],
		"explanation": "A GSA Schedules CTA is not a prime/sub arrangement: every teammate holds its own Schedule contract and deals directly with the Government for its portion. Option (b) describes the FAR 9.6 prime/subcontractor model, where only the prime has privity.",
		"citation": "FAR 9.601",
		"sourceUrl": "https://www.acquisition.gov/far/9.601",
		"tags": [
			"cta",
			"gsa-schedule",
			"privity",
			"prime-sub"
		]
	},
	{
		"id": "team-far-9601-two-forms",
		"unitId": "team",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "Under FAR 9.601, a 'contractor team arrangement' can take which two forms?",
		"options": [
			{
				"id": "a",
				"text": "(1) Two or more companies form a partnership or joint venture to act as a potential prime; or (2) a potential prime agrees with one or more companies to have them act as its subcontractors under a specified acquisition.",
				"correct": true
			},
			{
				"id": "b",
				"text": "(1) A prime and the Government jointly agree to share performance risk; or (2) two agencies combine their requirements into one contract.",
				"correct": false
			},
			{
				"id": "c",
				"text": "(1) A large business mentors a small business under an SBA agreement; or (2) two small businesses pool their past performance.",
				"correct": false
			},
			{
				"id": "d",
				"text": "(1) A prime hires temporary staff; or (2) a prime buys commercial items off a Schedule.",
				"correct": false
			}
		],
		"explanation": "FAR 9.601 defines a CTA as either a partnership/joint venture acting as a potential prime, or a potential prime plus one or more subcontractors teaming for a specified acquisition. Option (c) is the SBA mentor-protege construct, a different program.",
		"citation": "FAR 9.601",
		"sourceUrl": "https://www.acquisition.gov/far/9.601",
		"tags": [
			"cta",
			"definition",
			"joint-venture",
			"far-9-6"
		]
	},
	{
		"id": "team-losc-services-50-percent",
		"unitId": "team",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "Under the Limitations on Subcontracting clause (FAR 52.219-14) for a small-business set-aside for SERVICES (except construction), how much work must the prime keep?",
		"options": [
			{
				"id": "a",
				"text": "The prime may not pay more than 50% of the amount received for contract performance to firms that are not similarly situated entities.",
				"correct": true
			},
			{
				"id": "b",
				"text": "The prime must self-perform at least 15% of the cost of the contract.",
				"correct": false
			},
			{
				"id": "c",
				"text": "The prime must self-perform at least 25% of the cost of the contract.",
				"correct": false
			},
			{
				"id": "d",
				"text": "The prime must perform at least 51% of the total contract value, including the cost of materials.",
				"correct": false
			}
		],
		"explanation": "For services, 52.219-14 caps subcontracting to non-similarly-situated firms at 50% of the amount paid by the Government. The 15% figure is general construction and 25% is special-trade construction; the services test excludes materials.",
		"citation": "FAR 52.219-14",
		"sourceUrl": "https://www.acquisition.gov/far/52.219-14",
		"tags": [
			"limitations-on-subcontracting",
			"50-percent-rule",
			"services",
			"set-aside"
		]
	},
	{
		"id": "team-small-jv-size-rule",
		"unitId": "team",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "For a joint venture to qualify as small for a small-business set-aside, what is the size requirement for its members?",
		"options": [
			{
				"id": "a",
				"text": "Each member must individually qualify as small under the size standard, unless the JV is between an SBA-approved mentor and its protege, in which case the mentor may be large.",
				"correct": true
			},
			{
				"id": "b",
				"text": "Only the managing venturer must be small; the other members can be any size.",
				"correct": false
			},
			{
				"id": "c",
				"text": "The combined receipts or employees of all members, added together, must fall under the size standard.",
				"correct": false
			},
			{
				"id": "d",
				"text": "At least 51% of the JV must be owned by a small business, with no size limit on the minority members.",
				"correct": false
			}
		],
		"explanation": "Under 13 CFR 121.103(h), JV members are not aggregated; each must independently be small, with the sole exception of an SBA-approved mentor-protege JV (13 CFR 125.9), where the mentor can be other-than-small.",
		"citation": "13 CFR 121.103(h)",
		"sourceUrl": "https://www.ecfr.gov/current/title-13/section-121.103",
		"tags": [
			"joint-venture",
			"size",
			"mentor-protege",
			"small-business"
		]
	},
	{
		"id": "team-teaming-agreement-enforceability",
		"unitId": "team",
		"format": "scenario",
		"difficulty": "core",
		"scoring": "single-best",
		"situation": "You signed a teaming agreement naming a specialty firm as your subcontractor for 40% of the work if you win, but the subcontract price and detailed statement of work are 'to be negotiated in good faith after award.' You win the prime contract. The teammate now demands a much higher price and threatens to walk.",
		"prompt": "What is the realistic legal posture of your teaming agreement?",
		"options": [
			{
				"id": "a",
				"text": "Teaming agreements that leave material terms (price, SOW) to be negotiated later are frequently held to be unenforceable 'agreements to agree,' so you may have no remedy to force the teammate onto the subcontract.",
				"correct": true
			},
			{
				"id": "b",
				"text": "FAR 9.6 makes the teaming agreement automatically binding on both parties the moment you win the prime contract.",
				"correct": false
			},
			{
				"id": "c",
				"text": "The contracting officer will enforce the teaming agreement and direct the teammate to perform its 40%.",
				"correct": false
			},
			{
				"id": "d",
				"text": "The teammate is bound to the Government by privity of contract and cannot back out.",
				"correct": false
			}
		],
		"explanation": "The Government recognizes CTAs but does not become a party to or enforce them (FAR 9.603 - 9.604); enforceability is a matter of contract law between the parties, and courts routinely void teaming agreements whose key terms were left open. The sub has no privity with the Government.",
		"citation": "FAR 9.603",
		"sourceUrl": "https://www.acquisition.gov/far/9.603",
		"tags": [
			"teaming-agreement",
			"enforceability",
			"privity",
			"risk"
		]
	},
	{
		"id": "team-large-prime-set-aside-participation",
		"unitId": "team",
		"format": "scenario",
		"difficulty": "core",
		"scoring": "tiered",
		"situation": "You are a large business. A juicy opportunity is being set aside for small business, so you cannot bid as prime on your own. You want to participate as much as possible.",
		"prompt": "Which approach legitimately maximizes your role?",
		"options": [
			{
				"id": "a",
				"text": "Enter an SBA-approved mentor-protege joint venture with your protege small business, and have the JV bid as the small-business prime.",
				"tier": "best"
			},
			{
				"id": "b",
				"text": "Team as a subcontractor to a qualified small-business prime and take as large a workshare as the rules allow.",
				"tier": "defensible"
			},
			{
				"id": "c",
				"text": "Form an ordinary (non-mentor-protege) 50/50 joint venture with a small business.",
				"tier": "disqualifying"
			},
			{
				"id": "d",
				"text": "Self-certify the team as small based on your small teammate's size and bid as prime.",
				"tier": "disqualifying"
			}
		],
		"explanation": "A large business cannot be the prime on a small-business set-aside. The approved mentor-protege JV (13 CFR 125.9) is the one path that lets the large firm lead while the JV still qualifies as small; a plain JV with a large member is not small, and self-certifying as small is fraud.",
		"citation": "13 CFR 125.9",
		"sourceUrl": "https://www.ecfr.gov/current/title-13/section-125.9",
		"tags": [
			"mentor-protege",
			"set-aside",
			"joint-venture",
			"large-prime",
			"eligibility"
		]
	},
	{
		"id": "team-similarly-situated-entities",
		"unitId": "team",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "reveal-tradeoff",
		"situation": "You are a small-business prime on a services set-aside and want to keep only about 30% of the work in-house, pushing roughly 70% to teammates. The Limitations on Subcontracting clause (FAR 52.219-14) applies.",
		"prompt": "How do you allocate the 70% and stay compliant?",
		"options": [
			{
				"id": "a",
				"text": "Subcontract the 70% to a firm that holds the same small-business program status you do and is small for the NAICS code you assigned to the subcontract.",
				"tier": "best",
				"consequence": "Compliant: work by a similarly situated entity counts toward your side, so you + the SSE cover 100% and easily clear the 50% floor. You get the workshare flexibility you wanted."
			},
			{
				"id": "b",
				"text": "Subcontract the 70% to a large-business specialty firm that can do the work fastest.",
				"tier": "disqualifying",
				"consequence": "Violation: you self-perform only 30%, and the large sub is not similarly situated, so you breach the 50% limit. Risk of termination and False Claims exposure."
			},
			{
				"id": "c",
				"text": "Split the 70% among several other-than-small subcontractors so no single one is large.",
				"tier": "costly",
				"consequence": "Still noncompliant: all non-similarly-situated work counts against you regardless of how many firms you spread it across; you remain below 50% self-performance."
			},
			{
				"id": "d",
				"text": "Give the 70% to a small business that is small under a different NAICS code and a different program than yours.",
				"tier": "costly",
				"consequence": "Fails the test: it is not a 'similarly situated entity' for THIS award, so its work counts against your 50% and you are noncompliant."
			}
		],
		"explanation": "A 'similarly situated entity' is a subcontractor with the same small-business program status as the prime AND that is small for the NAICS the prime assigned to the subcontract. Work performed by an SSE is credited to the prime's side of the 50% calculation.",
		"citation": "FAR 52.219-14",
		"sourceUrl": "https://www.acquisition.gov/far/52.219-14",
		"tags": [
			"similarly-situated-entities",
			"limitations-on-subcontracting",
			"workshare",
			"compliance"
		]
	},
	{
		"id": "team-subcontracting-plan-threshold",
		"unitId": "team",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "confidence-bet",
		"situation": "You are a large (other-than-small) prime pursuing an unrestricted negotiated contract expected to be worth about $2 million, and the work has clear subcontracting opportunities.",
		"prompt": "What is true about a small-business subcontracting plan for this award?",
		"options": [
			{
				"id": "a",
				"text": "A subcontracting plan under FAR 19.702 / 52.219-9 is required, because the contract exceeds $900,000 and offers subcontracting possibilities and you are a large business.",
				"correct": true
			},
			{
				"id": "b",
				"text": "No plan is required because the value is above the simplified acquisition threshold, which exempts the contract.",
				"correct": false
			},
			{
				"id": "c",
				"text": "A plan is required only if the acquisition is set aside for small business.",
				"correct": false
			},
			{
				"id": "d",
				"text": "A plan is required only above $250,000, matching the simplified acquisition threshold.",
				"correct": false
			}
		],
		"explanation": "FAR 19.702 requires a subcontracting plan when a contract with a large business is expected to exceed $900,000 ($2 million for construction) and has subcontracting possibilities. Small-business primes and set-asides are exempt; the SAT ($250,000) is a different threshold.",
		"citation": "FAR 19.702",
		"sourceUrl": "https://www.acquisition.gov/far/19.702",
		"tags": [
			"subcontracting-plan",
			"far-19-7",
			"threshold",
			"large-prime"
		]
	},
	{
		"id": "propose-l-vs-m-sections",
		"unitId": "propose",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "In a negotiated RFP structured under the Uniform Contract Format (FAR 15.204-5), what does Section L tell offerors versus Section M?",
		"options": [
			{
				"id": "a",
				"text": "Section L gives instructions on how to prepare and submit the proposal; Section M states the factors and subfactors the Government will use to evaluate and make the award decision.",
				"correct": true
			},
			{
				"id": "b",
				"text": "Section L lists the evaluation factors for award; Section M gives instructions on proposal format and submission.",
				"correct": false
			},
			{
				"id": "c",
				"text": "Section L contains the contract clauses; Section M contains the representations and certifications.",
				"correct": false
			},
			{
				"id": "d",
				"text": "Section L is the statement of work; Section M is the pricing schedule.",
				"correct": false
			}
		],
		"explanation": "Under FAR 15.204-5, Section L = 'Instructions, conditions, and notices to offerors' (how to write and submit) and Section M = 'Evaluation factors for award' (how you'll be scored). Writing to L but ignoring M is the classic proposal error — you must build the proposal around the Section M factors while obeying the Section L instructions.",
		"citation": "FAR 15.204-5",
		"sourceUrl": "https://www.acquisition.gov/far/15.204-5",
		"tags": [
			"section-l",
			"section-m",
			"ucf",
			"proposal-structure"
		]
	},
	{
		"id": "propose-lpta-gold-plating",
		"unitId": "propose",
		"format": "scenario",
		"difficulty": "core",
		"scoring": "tiered",
		"situation": "The RFP's Section M states award will be made on a lowest-price, technically-acceptable (LPTA) basis, with technical rated only Acceptable/Unacceptable against defined minimum requirements. Your solution architects want to propose a premium, higher-availability design that beats every minimum, at a price about 12% above what a bare-minimum-compliant bid would cost.",
		"prompt": "As capture lead, how do you steer the bid strategy?",
		"options": [
			{
				"id": "a",
				"text": "Propose the leanest fully-compliant solution that clearly meets every stated minimum as 'Acceptable,' and drive price as low as defensible, since under LPTA nothing above acceptable earns credit.",
				"tier": "best"
			},
			{
				"id": "b",
				"text": "Propose a solid compliant baseline but include one or two low-cost enhancements clearly framed as no-added-cost, to differentiate on acceptability margin.",
				"tier": "defensible"
			},
			{
				"id": "c",
				"text": "Propose the premium high-availability design at the 12% higher price and rely on its technical superiority to justify the delta.",
				"tier": "costly"
			},
			{
				"id": "d",
				"text": "Bid below the minimum on a couple of requirements to win on price, planning to negotiate the gaps after award.",
				"tier": "disqualifying"
			}
		],
		"explanation": "FAR 15.101-2 LPTA makes tradeoffs impermissible: award goes to the lowest-priced proposal rated technically acceptable, so exceeding the minimums buys no evaluation credit and only raises your price. Meet every minimum cleanly and compete on price; a bid that misses a minimum is technically unacceptable and ineligible for award.",
		"citation": "FAR 15.101-2",
		"sourceUrl": "https://www.acquisition.gov/far/15.101-2",
		"tags": [
			"lpta",
			"best-value-continuum",
			"pricing-strategy"
		]
	},
	{
		"id": "propose-shall-compliance-matrix",
		"unitId": "propose",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "reveal-tradeoff",
		"situation": "Two days before the deadline, your compliance matrix flags one Section L 'shall': the past-performance volume 'shall be limited to five references, each no more than two pages.' Your draft has seven references and several run three pages. Section M says non-conforming proposals may be rejected without evaluation.",
		"prompt": "What do you do with the past-performance volume?",
		"options": [
			{
				"id": "a",
				"text": "Cut to your five strongest, most-relevant references and trim each to two pages before submitting.",
				"tier": "best",
				"consequence": "Fully compliant and responsive; the volume is evaluated on your best evidence and the proposal stays in the competition."
			},
			{
				"id": "b",
				"text": "Keep all seven but trim each to two pages, betting the evaluators want more data points.",
				"tier": "costly",
				"consequence": "Violates the five-reference 'shall'; the CO may reject the volume or count only the first five, and you've spent effort on references that won't be scored."
			},
			{
				"id": "c",
				"text": "Submit five references but leave them at three pages each because the content is strong.",
				"tier": "costly",
				"consequence": "Breaches the page 'shall'; evaluators may refuse to read past page two or find the volume non-conforming, so your strongest evidence goes unscored."
			},
			{
				"id": "d",
				"text": "Submit all seven at three pages and add a note asking the CO to waive the limit given your strong record.",
				"tier": "disqualifying",
				"consequence": "Doubly non-compliant with a 'shall'; the CO can reject the proposal without evaluation and there is no obligation to waive a stated limit."
			}
		],
		"explanation": "In a Section L compliance matrix, every 'shall' is a mandatory instruction; a proposal that ignores one is non-conforming and may be rejected or have the offending material disregarded. Being responsive to the instructions is a threshold gate — winning content that violates a 'shall' can be thrown out before it's ever scored.",
		"citation": "FAR 15.204-5",
		"sourceUrl": "https://www.acquisition.gov/far/15.204-5",
		"tags": [
			"compliance-matrix",
			"shall",
			"responsiveness",
			"section-l"
		]
	},
	{
		"id": "propose-neutral-past-performance",
		"unitId": "propose",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "confidence-bet",
		"situation": "You're pursuing a new market where your firm has no relevant prior contracts. A competitor's BD lead tells you not to bother bidding because 'no past performance means an automatic low score that kills you.'",
		"prompt": "Under FAR 15.305, how is an offeror with no relevant past-performance record supposed to be treated in the past-performance evaluation?",
		"options": [
			{
				"id": "a",
				"text": "It must be evaluated neither favorably nor unfavorably on past performance — a neutral/unknown-confidence rating.",
				"correct": true
			},
			{
				"id": "b",
				"text": "It automatically receives the lowest past-performance rating, since absence of a record is treated as poor performance.",
				"correct": false
			},
			{
				"id": "c",
				"text": "It is found ineligible for award because past performance is a mandatory pass/fail responsibility gate.",
				"correct": false
			},
			{
				"id": "d",
				"text": "The Government must substitute the past performance of the offeror's proposed subcontractors as if it were the prime's own.",
				"correct": false
			}
		],
		"explanation": "FAR 15.305(a)(2)(iv) requires that an offeror without a relevant past-performance record 'may not be evaluated favorably or unfavorably' — a neutral rating, not a penalty. The competitor's claim is a myth; a lack of history is a differentiator problem, not a disqualifier.",
		"citation": "FAR 15.305",
		"sourceUrl": "https://www.acquisition.gov/far/15.305",
		"tags": [
			"past-performance",
			"neutral-rating",
			"new-entrant"
		]
	},
	{
		"id": "win-protest-debrief-request-window",
		"unitId": "win-protest",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "After losing a competitive award, your team wants a required post-award debriefing so you can see how you were scored. By when must you request it to be entitled to one?",
		"options": [
			{
				"id": "a",
				"text": "In writing, within 3 days after receiving notification of contract award",
				"correct": true
			},
			{
				"id": "b",
				"text": "In writing, within 5 days after receiving notification of contract award",
				"correct": false
			},
			{
				"id": "c",
				"text": "In writing, within 10 days after receiving notification of contract award",
				"correct": false
			},
			{
				"id": "d",
				"text": "Any time before you file a GAO protest",
				"correct": false
			}
		],
		"explanation": "FAR 15.506(a) requires the written debriefing request to reach the contracting officer within 3 days after the offeror receives notification of contract award; a required, timely-requested debriefing is what unlocks the more generous protest and CICA-stay clocks. The 5- and 10-day figures are protest/stay deadlines, not the debriefing-request deadline.",
		"citation": "FAR 15.506(a)",
		"sourceUrl": "https://www.acquisition.gov/far/15.506",
		"tags": [
			"debriefing",
			"post-award",
			"far-15"
		]
	},
	{
		"id": "win-protest-preaward-solicitation-defect",
		"unitId": "win-protest",
		"format": "recall",
		"difficulty": "fundamentals",
		"scoring": "single-best",
		"prompt": "The RFP contains an evaluation criterion you believe is unduly restrictive and improper on its face. To keep a GAO protest of that solicitation defect timely, when must you file?",
		"options": [
			{
				"id": "a",
				"text": "Before the closing time for receipt of proposals",
				"correct": true
			},
			{
				"id": "b",
				"text": "Within 10 days after contract award",
				"correct": false
			},
			{
				"id": "c",
				"text": "Within 10 days after you learn who won",
				"correct": false
			},
			{
				"id": "d",
				"text": "Within 5 days after your post-award debriefing",
				"correct": false
			}
		],
		"explanation": "Alleged solicitation improprieties apparent on the face of the solicitation must be protested before the deadline for receipt of proposals (FAR 33.104; GAO timeliness rules at 4 CFR 21.2(a)(1)). You cannot sit on a known solicitation defect, compete, lose, and then raise it post-award — that ground is waived. The 10-day and 5-day windows apply to other-than-solicitation grounds and the stay, not to face-of-the-solicitation defects.",
		"citation": "FAR 33.104",
		"sourceUrl": "https://www.acquisition.gov/far/33.104",
		"tags": [
			"gao-protest",
			"pre-award",
			"timeliness",
			"far-33"
		]
	},
	{
		"id": "win-protest-forum-choice",
		"unitId": "win-protest",
		"format": "scenario",
		"difficulty": "core",
		"scoring": "tiered",
		"situation": "Two days after a post-award debriefing you're convinced the agency misapplied the stated evaluation criteria. You want an independent review, a realistic shot at halting performance, and to keep cost and time low. You're still inside the window that would trigger an automatic suspension of performance.",
		"prompt": "Which protest forum best fits these goals right now?",
		"options": [
			{
				"id": "a",
				"text": "File a protest at GAO within the stay window",
				"tier": "best"
			},
			{
				"id": "b",
				"text": "File an agency-level protest with the contracting agency",
				"tier": "defensible"
			},
			{
				"id": "c",
				"text": "File a bid-protest action at the Court of Federal Claims",
				"tier": "costly"
			},
			{
				"id": "d",
				"text": "File a complaint with the SBA and the agency Inspector General",
				"tier": "disqualifying"
			}
		],
		"explanation": "GAO is the sweet spot here: an independent forum, a statutory ~100-day decision clock, low relative cost, and — filed inside the window — the CICA automatic stay (FAR 33.104). An agency-level protest is faster and cheaper but decided by the same agency (FAR 33.103). COFC is a legitimate forum but has no automatic stay and is slower/costlier — better as a fallback if GAO deadlines lapse. SBA/IG complaints are not bid-protest forums at all and give you no protest relief.",
		"citation": "FAR 33.104",
		"sourceUrl": "https://www.acquisition.gov/far/33.104",
		"tags": [
			"protest-forum",
			"gao",
			"agency-protest",
			"cofc",
			"far-33"
		]
	},
	{
		"id": "win-protest-cica-stay-timing",
		"unitId": "win-protest",
		"format": "scenario",
		"difficulty": "advanced",
		"scoring": "reveal-tradeoff",
		"situation": "You lost a $40M award. You timely requested and received a required post-award debriefing, which closed today. You have a strong evaluation-error protest ground and — critically — you want to stop the awardee from performing while GAO decides. Cash and schedule pressure mean an automatic suspension of performance is worth more to you than the protest itself.",
		"prompt": "What filing action best protects your position?",
		"options": [
			{
				"id": "a",
				"text": "File the protest at GAO within 5 days after the close of the required debriefing",
				"tier": "best",
				"consequence": "Triggers the CICA automatic stay under 31 U.S.C. 3553(d) — the agency must suspend the awardee's performance pending GAO's decision, exactly the leverage you wanted."
			},
			{
				"id": "b",
				"text": "File the protest at GAO on the 9th day after the debriefing (still inside GAO's 10-day merits deadline)",
				"tier": "defensible",
				"consequence": "Protest is timely and GAO hears it on the merits, but you blew the 5-day stay window — no automatic stay, so the awardee keeps performing and any win may be hollow."
			},
			{
				"id": "c",
				"text": "Skip GAO and file suit at the Court of Federal Claims",
				"tier": "costly",
				"consequence": "COFC is a valid forum but grants no automatic stay — you'd have to separately win a preliminary injunction (higher bar, slower, costlier), so performance continues in the meantime."
			},
			{
				"id": "d",
				"text": "Wait until you receive GAO's docketing notice, about 15 days after the debriefing, then file",
				"tier": "disqualifying",
				"consequence": "Untimely — past both the 5-day stay window and GAO's 10-day merits deadline; the protest is dismissed, no stay and no review."
			}
		],
		"explanation": "To get the CICA automatic stay you must file with GAO within the later of 10 days after award or 5 days after a required, timely-requested debriefing (31 U.S.C. 3553(d); FAR 33.104). After a required debriefing, the 5-day post-debriefing clock is the operative one — miss it and you may still have a timely protest but lose the suspension of performance.",
		"citation": "FAR 33.104",
		"sourceUrl": "https://www.acquisition.gov/far/33.104",
		"tags": [
			"cica-stay",
			"gao-protest",
			"post-award",
			"far-33"
		]
	}
];
